[package]
name = "farm-extra-rewards-wrapper-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["you"]

[dev-dependencies]

[dependencies.farm-extra-rewards-wrapper]
path = ".."

[dependencies.dharitri-sc-meta]
version = "=0.13.6"
default-features = false
